language: java

stages:
  - compile
  - test
  - name: deploy
    if: branch = master # déploiement conditionnel
    
jobs:
  include:
    - stage: compile
      script: mvn compile
    
    
    - stage: test
      script: mvn test
     
    - stage: deploy
      script: mvn install
